#!/bin/sh

output_user() {
    echo "testuser:x:5000:5000:Map everyone to one account:/home/testuser:/bin/sh"
}

case "$1" in
    getpwent)
        # Gets the password entry.  We're simulating only entry 1 existing
        if [ "$2" = "0" ]; then
            output_user
            exit 0
        fi

        # Return code 1 = user not found
        exit 1
        ;;

    getpwnam)
        # Always "find" testuser.  This maps all incoming users to testuser.
        output_user
        exit 0
        ;;

    getpwuid)
        if [ "$2" = "5000" ]; then
            output_user
            exit 0
        fi

        # Return code 1 = user not found
        exit 1
        ;;
esac

# Return code 4 = service unavailable
exit 4
