#!/bin/bash

case "$1" in
    setspent|endspent)
        exit 0
        ;;

    getspent)
        case "$2" in
            0)
                echo "user123:password123:12345:0:99999:1:2:3:4:5"
                exit 0
                ;;

            1)
                echo "user456:password456:54321:99999:0"
                exit 0
                ;;

            2)
                echo "user789:password789:99110:12345:88888:22:33:44:55"
                exit 0
                ;;

            3)
                exit 1
        esac
        ;;
esac

exit 1
